### ISSUE TITLE
Make css from sphinx_book_theme inheritable

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-sphinx-book-theme#7]
Despite specifying this inheritance in `theme.conf`
https://github.com/pangeo-forge/pangeo-sphinx-book-theme/blob/787b3d7f80ed55cee636a301b668c0b2b0d42365/pangeo_sphinx_book_theme/theme.conf#L1-L2

... I still needed to manually add the sphinx_book_theme css styles to the top of the custom css for this theme:
https://github.com/pangeo-forge/pangeo-sphinx-book-theme/blob/787b3d7f80ed55cee636a301b668c0b2b0d42365/pangeo_sphinx_book_theme/static/custom.css#L1-L5

(Without this direct copy-and-paste from the sphinx_book_theme, the styles did not work correctly.)

It seems like this should not be necessary, but I am not sure how (or if) it is possible to get the styles properly loaded without it.

**Comment by rabernat** [comment]
Can you use a [css import rule](https://www.w3schools.com/cssref/pr_import_rule.asp) to import the "upstream" stylesheet from sphinx_book_theme?

**Comment by cisaacstern** [comment]
Good thought; that would certainly be a cleaner way of implementing the same notion.

Perhaps I've misunderstood the idea of sphinx inheritance, but somehow I'd imagined that the parent theme's styles would be automatically passed to the child theme. So it was odd to me that this copy-and-paste (or a more graceful `@import`) would be required at all. 

Not really a big deal I suppose, if it works, but I'll be curious to learn more about this as time goes on.

**Comment by rabernat** [comment]
I'm sure the folks over at https://github.com/executablebooks/sphinx-book-theme would be happy to help. @choldgraf is one the the lead devs and a very close collaborator.

**Comment by choldgraf** [comment]
hmmm, indeed it is strange, I'd assume that all of the CSS would be inherited as well 🤔 did the CSS make it into your site's generated HTML files?

(also out of curiosity why are you creating a new sub-theme? you might be able to accomplish your goal by just including your own custom CSS etc)

**Comment by rabernat** [comment]
> also out of curiosity why are you creating a new sub-theme?

We want to use the same styling on many different sites. See https://github.com/pangeo-forge/pangeo-forge-recipes/issues/126.

**Comment by cisaacstern** [comment]
> did the CSS make it into your site's generated HTML files?

As far as I could tell, they were not passing through to the generated HTML files. I ultimately figured this out by `diff`ing  two `_build/html/` directories (one from before packaging, and one from after). I wish I had a more productive snapshot of this to share here, but the evidence was ultimately lost in a frenzy of trial-and-error. 😅 (Note to self: keep records next time.)

> you might be able to accomplish your goal by just including your own custom CSS etc

Yes, I realized about 3/4 of the way through, that this is basically all we are doing at this point: i.e. making a single CSS file pip-installable alongside the parent theme. Admittedly the overhead-to-benefit ratio may be a bit high, but given the large number of sites which may eventually use this color scheme, perhaps it is worth it to be able to keep any future stylistic changes in sync.

**Comment by choldgraf** [comment]
> We want to use the same styling on many different sites

Ah cool - though one thought, couldn't you just define one CSS file (e.g., in a github repository) and then link to it in the sphinx setup with

```python
def setup(app):
  app.add_css_file(url-for-your-css-file)
```

?

That might be a bit simpler than defining your own sub-theme.

to try it out, what happens if you added this:

```python
def setup(app):
  app.add_css_file("https://raw.githubusercontent.com/executablebooks/sphinx-book-theme/master/sphinx_book_theme/static/sphinx-book-theme.css")
```

**Comment by cisaacstern** [comment]
> link to it in the sphinx setup with

Forgive the n00b question, but I'm not clear what you mean by "sphinx setup" here. Is there a `setup.py` that I'm overlooking somewhere?

We previously included the custom styles in the sphinx `conf.py` with
```python
html_css_files = ["custom.css",]
```
...but of course this required keeping `custom.css` in the project repo.

This is not an urgent item, but will so appreciate your feedback as time allows.
